import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Factory",
  description: "Generated by create next app",
};

const Nav = () => (
  <nav className="NavigationBar">
    <Link href="/machines">
      Machines
    </Link>
    <Link href="/sensors">
      Sensors
    </Link>
    <Link href="/production-sequences">
      Production Sequences
    </Link>
    <Link href="/analytics">
      Analytics
    </Link>
  </nav>
);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{
        <section>
          <Nav />
          {children}
        </section>
      }</body>
    </html>
  );
}
